# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Reputer < Formula
  desc "CLI tool that calculates contributor reputation scores from Git provider APIs"
  homepage "https://github.com/mchmarny/reputer"
  version "0.4.5"
  license "Apache-2.0"

  on_macos do
    url "https://github.com/mchmarny/reputer/releases/download/v0.4.5/reputer_0.4.5_darwin_all"
    sha256 "e943764dea9c664194b930c38c67f7bc67f0a08d3959442a5b4f0e5d7d58f0ef"

    define_method(:install) do
      bin.install "reputer_0.4.5_darwin_all" => "reputer"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mchmarny/reputer/releases/download/v0.4.5/reputer_0.4.5_linux_amd64"
      sha256 "c1f28991e363abc2314099fcd7c47403fe0b873a3188c2d58c2c4f0f754f7e60"
      define_method(:install) do
        bin.install "reputer_0.4.5_linux_amd64" => "reputer"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mchmarny/reputer/releases/download/v0.4.5/reputer_0.4.5_linux_arm64"
      sha256 "c46eba27a171c5ab9c09d985b83aaed973eceba8e915b23f4acfcc9747133538"
      define_method(:install) do
        bin.install "reputer_0.4.5_linux_arm64" => "reputer"
      end
    end
  end

  test do
    system "#{bin}/reputer" "--version"
  end
end
