# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Reputer < Formula
  desc "CLI tool that calculates contributor reputation scores from Git provider APIs"
  homepage "https://github.com/mchmarny/reputer"
  version "0.5.0"
  license "Apache-2.0"

  on_macos do
    url "https://github.com/mchmarny/reputer/releases/download/v0.5.0/reputer_0.5.0_darwin_all"
    sha256 "ba0d8c308686f3969dda5418223f22fef1c88a22fa3f69b8d98592455569b446"

    define_method(:install) do
      bin.install "reputer_0.5.0_darwin_all" => "reputer"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mchmarny/reputer/releases/download/v0.5.0/reputer_0.5.0_linux_amd64"
      sha256 "73b848bd78ac820ab4ea7d9929f992f384949a732b1a6aa04eebe9a8c18fd42e"
      define_method(:install) do
        bin.install "reputer_0.5.0_linux_amd64" => "reputer"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mchmarny/reputer/releases/download/v0.5.0/reputer_0.5.0_linux_arm64"
      sha256 "c0387f1d6456535747c12bd82ae0f8295aad81bea1218b03b2b68d7ebea3cc00"
      define_method(:install) do
        bin.install "reputer_0.5.0_linux_arm64" => "reputer"
      end
    end
  end

  test do
    system "#{bin}/reputer" "--version"
  end
end
