# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dctl < Formula
  desc "Simple utility to provide insight into repo activity."
  homepage "https://github.com/mchmarny/dctl"
  version "0.5.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mchmarny/dctl/releases/download/v0.5.0/dctl_darwin_amd64"
      sha256 "c221addf6d06fad5c7405d25ea9d448cc21592d4f410c18ac1ea327c2d4f0229"

      def install
        bin.install "dctl_darwin_amd64" => "dctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mchmarny/dctl/releases/download/v0.5.0/dctl_darwin_arm64"
      sha256 "a5c513b8e7e39048b741e80f08977a5c78946d5c7f4b9ebdda3adc1ef9ced14b"

      def install
        bin.install "dctl_darwin_arm64" => "dctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mchmarny/dctl/releases/download/v0.5.0/dctl_linux_amd64"
      sha256 "838f6596771fcc4d443538df09df06edda0ce45d02a470ccaf20bb8a8eff27f0"
      def install
        bin.install "dctl_linux_amd64" => "dctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mchmarny/dctl/releases/download/v0.5.0/dctl_linux_arm64"
      sha256 "f6b11ccfc4ff5c3a0adc5afa9a806fbf96e08e070871e45bc740c2b4821a90cc"
      def install
        bin.install "dctl_linux_arm64" => "dctl"
      end
    end
  end
end
