# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Devpulse < Formula
  desc "Community health analytics for GitHub organizations and repositories"
  homepage "https://github.com/mchmarny/devpulse"
  version "0.17.4"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mchmarny/devpulse/releases/download/v0.17.4/devpulse_darwin_amd64.tar.gz"
      sha256 "30fbc2a30f334faaf2ba1753f37c5701629b316a7d90b6a220a83af4b5c6e3c1"

      define_method(:install) do
        bin.install "devpulse"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mchmarny/devpulse/releases/download/v0.17.4/devpulse_darwin_arm64.tar.gz"
      sha256 "6c9b15775a07f8683a7a8f044284d6b14afd8cf2e97ce9ed5a96d14becb4a806"

      define_method(:install) do
        bin.install "devpulse"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mchmarny/devpulse/releases/download/v0.17.4/devpulse_linux_amd64.tar.gz"
      sha256 "735bc8279c9bf5b9b445c59ede4dc87c6819157d5f93d0fb662e453471b54fd2"
      define_method(:install) do
        bin.install "devpulse"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mchmarny/devpulse/releases/download/v0.17.4/devpulse_linux_arm64.tar.gz"
      sha256 "02fd7151924f288c61be51b46a6aeba7b4b36f8ac5ac5936798758e9420ce003"
      define_method(:install) do
        bin.install "devpulse"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/devpulse version")
  end
end
