# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Reputer < Formula
  desc "CLI tool to calculate contributor reputation from Git providers"
  homepage "https://github.com/mchmarny/reputer"
  version "0.4.4"
  license "Apache-2.0"

  on_macos do
    url "https://github.com/mchmarny/reputer/releases/download/v0.4.4/reputer_0.4.4_darwin_all"
    sha256 "a309d60d885a7d3d2f2ac632884fe9cbdb8b89b54cf06a55732b3f83a44f90af"

    define_method(:install) do
      bin.install "reputer_0.4.4_darwin_all" => "reputer"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mchmarny/reputer/releases/download/v0.4.4/reputer_0.4.4_linux_amd64"
      sha256 "b63d5b3b1ea520a15bfea817fa101c9f5c8715e9ec64a328f7da0baab217fc4d"
      define_method(:install) do
        bin.install "reputer_0.4.4_linux_amd64" => "reputer"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mchmarny/reputer/releases/download/v0.4.4/reputer_0.4.4_linux_arm64"
      sha256 "a3a97e384728361866b4626f0b24b7aad45ad73b1b15a026a8f4e99a6f297af1"
      define_method(:install) do
        bin.install "reputer_0.4.4_linux_arm64" => "reputer"
      end
    end
  end

  test do
    system "#{bin}/reputer" "--version"
  end
end
